{
 "title": "WEB",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU UTIL  web-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.0.1.3:9100\"}[1m]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB1 MEM UTILS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes{job=\"prometheus\", instance=\"10.0.1.3:9100\"}) / sum(node_memory_MemTotal_bytes{job=\"prometheus\", instance=\"10.0.1.3:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB1 DISK SATUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "avg by(job) (irate(node_disk_io_time_weighted_seconds_total{job=\"prometheus\", device=\"vda\", instance=\"10.0.1.3:9100\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU UTIL  web-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.0.1.3:9100\"}[1m]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB2 MEM UTILS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes{job=\"prometheus\", instance=\"10.0.2.3:9100\"}) / sum(node_memory_MemTotal_bytes{job=\"prometheus\", instance=\"10.0.2.3:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB2 DISK SATUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "avg by(job) (irate(node_disk_io_time_weighted_seconds_total{job=\"prometheus\", device=\"vda\", instance=\"10.0.2.3:9100\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Saturation web1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_load1{instance=\"10.0.1.3:9100\", job=\"prometheus\"}) / sum(count(node_cpu_seconds_total{instance=\"10.0.1.3:9100\", job=\"prometheus\", mode=\"idle\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB1 - MEM Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "1e3 * sum( rate(node_vmstat_pgpgin{instance=\"10.0.1.3:9100\", job=\"prometheus\"}[1m]) + rate(node_vmstat_pgpgout{instance=\"10.0.1.3:9100\", job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB1 DISK UTILS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"10.0.1.3:9100\", job=\"prometheus\", device=\"vda\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Saturation web2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_load1{instance=\"10.0.2.3:9100\", job=\"prometheus\"}) / sum(count(node_cpu_seconds_total{instance=\"10.0.2.3:9100\", job=\"prometheus\", mode=\"idle\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB2 - MEM Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "1e3 * sum( rate(node_vmstat_pgpgin{instance=\"10.0.2.3:9100\", job=\"prometheus\"}[1m]) + rate(node_vmstat_pgpgout{instance=\"10.0.2.3:9100\", job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB2 DISK UTILS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"10.0.2.3:9100\", job=\"prometheus\", device=\"vda\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web1 respons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (rate(nginx_http_response_count_total{job=\"prometheus\", instance=\"10.0.1.3:4040\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web1 SIZE RESPONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(nginx_http_response_size_bytes{job=\"prometheus\", instance=\"10.0.1.3:4040\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB1 DROP",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (rate(node_network_transmit_bytes_total{job=\"prometheus\", instance=\"10.0.1.3:9100\", device=\"eth0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web2respons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (rate(nginx_http_response_count_total{job=\"prometheus\", instance=\"10.0.2.3:4040\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web2 SIZE RESPONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(nginx_http_response_size_bytes{job=\"prometheus\", instance=\"10.0.2.3:4040\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB2 DROP",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (rate(node_network_transmit_bytes_total{job=\"prometheus\", instance=\"10.0.2.3:9100\", device=\"eth0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB1 TRANSMIT",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(node_network_receive_bytes_total{job=\"prometheus\", instance=\"10.0.1.3:9100\", device=\"eth0\"}[5m])) + sum by(job) (rate(node_network_transmit_bytes_total{job=\"prometheus\", instance=\"10.0.1.3:9100\", device=\"eth0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB2 TRANSMIT",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(node_network_receive_bytes_total{job=\"prometheus\", instance=\"10.0.2.3:9100\", device=\"eth0\"}[5m])) + sum by(job) (rate(node_network_transmit_bytes_total{job=\"prometheus\", instance=\"10.0.2.3:9100\", device=\"eth0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}