##################################
##### ПОЕХАЛИ! (с) Ю.Гагарин #####
##################################
---
- hosts: elastic
  name: Install Elasticsearch
  become: true
  roles:
    - elastic

- hosts: kibana
  name: Install kibana for Elasticsearch
  become: true
  roles:
    - kibana

- hosts: web
  name: Install Nginx, Node Exporter, Nginx Log Exporter, Filebeat
  become: true
  roles:
   - web
   - filebeat

- hosts: prometheus
  name: Install prometheus
  become: true
  roles:
   - prometheus

- hosts: grafana
  name: Install Grafana
  become: true
  roles:
   - grafana